import './globals.css'
import { Providers } from "@/redux/provider"
import Toaster from './utils/components/Toaster'

export const metadata = {
  title: 'PCLMS - Laboratory Management System',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.cdnfonts.com/css/plance" rel="stylesheet" />
      </head>
      <body>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  )
}
