export { default as Title } from '@/app/utils/components/Title'
export { default as SuspenseLoader } from '@/app/components/Loader'
export { default as EmptyList } from '@/app/utils/components/EmptyList'
export { default as EquipmentList } from '@/app/admin/equipment/components/List'
export { default as Search } from '@/app/admin/equipment/components/Prompts/Search'
export { default as Filter } from '@/app/admin/equipment/components/Prompts/Filter'