export { default as Title } from '@/app/utils/components/Title'
export { default as DataDisplay } from './components/DataDisplay'
export { default as Texts } from './components/Texts'
export { default as Preview } from './components/Prompts/Preview'
export { default as Update } from './components/Prompts/Update'
export { default as Remove } from './components/Prompts/Remove'
export { default as SuspenseLoader } from '@/app/components/Loader'
export { default as PhotoDisplayer } from './components/PhotoDisplayer'